[project]
name = "ans-workstation"
version = "1.0.1"
dependencies = [
    "ansible-lint",
    "ansible",
    "jmespath",
    "yamllint",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
